# Generated by Django 2.2 on 2019-06-10 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='req',
            name='req_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='req',
            name='req_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
