# Generated by Django 2.2 on 2019-06-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190610_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='is_fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
